imshow(uint8(frame_cortado));
raio = 8;
rectangle('Position', [Vermelho_centros(1,:) - raio, 2 * raio, 2 * raio], ...
          'Curvature', [1, 1], 'EdgeColor', 'r', 'LineWidth', 3);
rectangle('Position', [Vermelho_centros(2,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'r', 'LineWidth', 3);
rectangle('Position', [laranja_centro - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'y', 'LineWidth', 3);
rectangle('Position', [magenta_centros(1,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'm', 'LineWidth', 3);
rectangle('Position', [magenta_centros(2,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'm', 'LineWidth', 3);
rectangle('Position', [magenta_centros(3,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'm', 'LineWidth', 3);
rectangle('Position', [magenta_centros(4,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'm', 'LineWidth', 3);
rectangle('Position', [amarelo_centros(1,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'y', 'LineWidth', 3);
rectangle('Position', [amarelo_centros(2,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'y', 'LineWidth', 3);
rectangle('Position', [amarelo_centros(3,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'y', 'LineWidth', 3);
rectangle('Position', [verde_centros(1,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'g', 'LineWidth', 3);
rectangle('Position', [verde_centros(2,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'g', 'LineWidth', 3);
rectangle('Position', [verde_centros(3,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'g', 'LineWidth', 3);
rectangle('Position', [verde_centros(4,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'g', 'LineWidth', 3);
rectangle('Position', [verde_centros(5,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'g', 'LineWidth', 3);
rectangle('Position', [verde_centros(6,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'g', 'LineWidth', 3);
rectangle('Position', [azul_centros(1,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'b', 'LineWidth', 3);
rectangle('Position', [azul_centros(2,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'b', 'LineWidth', 3);
rectangle('Position', [azul_centros(3,:) - raio, 2 * raio, 2 * raio], ...
  'Curvature', [1, 1], 'EdgeColor', 'b', 'LineWidth', 3);


